dist: xenial
language: python
cache: pip
python: "3.7"

env:
  - TOXENV=py37
  - TOXENV=lint
  - TOXENV=doctest

install:
  - travis_retry pip install tox
  - if [[ $TOXENV == py37 ]]; then travis_retry pip install coveralls; fi
script:
  - tox
after_success:
  - if [[ $TOXENV == py37 ]]; then coveralls; fi
